Data:
    orbit_file: /data/leuven/367/vsc36785/LISA/Mojito_analysis/esa-trailing-orbits-mojito_validation_test_2.h5
    mojito_l1_file: /scratch/leuven/367/vsc36785/MojitoLight/SIM_data/brickmarket/mojito_light_v1_0_0/data/EMRI/L1/EMRI_731d_2.5s_L1_source0_0_20251203T225446987631Z.h5
    noise_file: /scratch/leuven/367/vsc36785/MojitoLight/SIM_data/brickmarket/mojito_light_v1_0_0/data/NOISE/L1/NOISE_731d_2.5s_L1_source0_0_20251206T220508924302Z.h5

Injection:
    EMRI:
        # masses are source frame masses and will be redshifted with parameter z. 
        M: 1000000.0
        mu: 10.0
        a: 0.00002
        p0: 9.0
        e0: 0.0
        x_I0: 1.0
        d_L: 0.1
        theta_S: 0.5689062462243505
        phi_S: 3.069569972026508
        theta_K: 0.11247032308126413
        phi_K: 0.7524383205999023
        Phi_phi0: 4.809727148143657
        Phi_theta0: 0.635376120342196
        Phi_r0: 4.2638433178190684
        chi2: 0.9
        z: 1

    Waveform:
        model: 1PAT1R              # '1PAT1R' or '0PA_Kerr'
        evolve_chi1: true
        include_1PA_amps: true
        dt: 5
        T: 2
        mode_selection_threshold: 0.0
        inspiral_kwargs:
            DENSE_STEPPING: 0
            max_init_len: 1000
        summation_kwargs:
            pad_output: true
        amplitude_kwargs: {}

Response:
    tdi_gen: '2nd generation'
    tdi_chan: XYZ                  # 'XYZ' or 'AET'
    order: 40
    offset: 550
    n_samples_delay: 1000
    t_buffer: 10000.0
    flip_hx: true
    is_ecliptic_latitude: false

Recovery:
    # Waveform settings for the recovery template. Leave equal to injection
    # for a self-consistent test; toggle for systematics studies.
    Waveform:
        model: 1PAT1R
        evolve_chi1: true
        include_1PA_amps: true
        dt: 5
        T: 2
        mode_selection_threshold: 0.0
        inspiral_kwargs:
            DENSE_STEPPING: 0
            max_init_len: 1000
        summation_kwargs:
            pad_output: true
        amplitude_kwargs: {}

Sampler:
    name: test_1
    windowing: true
    filter_freq: true
    num_samples: 10000
    burn_in: 0
    use_gpu: true
    n_temps: 3
    n_walkers: 30
    d: 5
    continue_run: false
    sampling_data_path: ./sampling_data
    plots_path: ./Plots
    fixed_params: ['x_I0', 'e0']
